'use client';
import type { Metadata } from 'next';
import './globals.css';
import NavBar from './ui/navbar/navbar';


// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={"w-full h-full inset-0 bg-gradient-to-b from-[#FD8653] via-[#FFC363] to-[#FD8653] opacity-100"}>
        <div className='bg-pucuk-rebung bg-repeat-y bg-center bg-[length:100%]'>
          {children}
        </div>
      </body>
    </html>
  );
}
