export const mediaLogos = [
    { src: "/jmun media logos/(Psiaga) Logo + Typography.webp", alt: "Psiaga Logo Typography" },
    { src: "/jmun media logos/2._UI_MUN_Club_Logo-removebg-preview-crop.webp", alt: "UI MUN Club Logo" },
    { src: "/jmun media logos/AIESEC in Universitas Brawijaya [black].webp", alt: "AIESEC Universitas Brawijaya" },
    { src: "/jmun media logos/alsa_e-comp_ui_logo-removebg-preview.webp", alt: "ALSA E-Comp UI Logo" },
    { src: "/jmun media logos/birds binus.webp", alt: "Birds Binus" },
    { src: "/jmun media logos/Blue Logo Icon.webp", alt: "Blue Logo Icon" },
    { src: "/jmun media logos/BTB MUN (transparent).webp", alt: "BTB MUN" },
    { src: "/jmun media logos/BWHitam_Transparan.webp", alt: "BW Hitam Transparan" },
    { src: "/jmun media logos/CIRCLE MAKSMUN 2024 LOGO.webp", alt: "Circle MAKSMUN 2024 Logo" },
    { src: "/jmun media logos/Copy of logo vetamun recolor transparent (1).webp", alt: "Vetamun Recolor Transparent" },
    { src: "/jmun media logos/diponegoro_mun_society-1-removebg-preview.webp", alt: "Diponegoro MUN Society" },
    { src: "/jmun media logos/FKHMII.webp", alt: "FKHMII" },
    { src: "/jmun media logos/FPCI Unsoed.webp", alt: "FPCI Unsoed" },
    { src: "/jmun media logos/fpci_chapter_upnvj_logo-removebg-preview.webp", alt: "FPCI Chapter UPNVJ" },
    { src: "/jmun media logos/fpci_ui-removebg-preview.webp", alt: "FPCI UI" },
    { src: "/jmun media logos/GDS-removebg-preview.webp", alt: "GDS" },
    { src: "/jmun media logos/gpykorea logo.webp", alt: "GPY Korea Logo" },
    { src: "/jmun media logos/impactional.webp", alt: "Impactional" },
    { src: "/jmun media logos/IR_PRO-removebg-preview.webp", alt: "IR PRO" },
    { src: "/jmun media logos/itbmun-ezgif.com-jpg-to-webp-converter.webp", alt: "ITB MUN" },
    { src: "/jmun media logos/ITS MUN Club Black.webp", alt: "ITS MUN Club Black" },
    { src: "/jmun media logos/Kompasiana-putih-ezgif.com-jpg-to-webp-converter.webp", alt: "Kompasiana Putih" },
    { src: "/jmun media logos/Kontekstual-removebg-preview.webp", alt: "Kontekstual" },
    { src: "/jmun media logos/Logo Produktifkuy.webp", alt: "Produktifkuy" },
    { src: "/jmun media logos/Logo Radio PPI Dunia Bright Transparent.webp", alt: "Radio PPI Dunia" },
    { src: "/jmun media logos/Logo RPD - Black.webp", alt: "RPD Black" },
    { src: "/jmun media logos/Logo_MAM_UP-removebg-preview.webp", alt: "MAM UP" },
    { src: "/jmun media logos/Logo_Milenianews-removebg-preview.webp", alt: "Milenianews" },
    { src: "/jmun media logos/LOGO_RTC_UI-removebg-preview.webp", alt: "RTC UI" },
    { src: "/jmun media logos/LogoAIESECUNTAN-ezgif.com-jpg-to-webp-converter.webp", alt: "AIESEC UNTAN" },
    { src: "/jmun media logos/LOGOFPCICHAPTERBINUS-ezgif.com-jpg-to-webp-converter.webp", alt: "FPCI Chapter BINUS" },
    { src: "/jmun media logos/LOGOLSPRBLACK-ezgif.com-jpg-to-webp-converter.webp", alt: "LSPR Black" },
    { src: "/jmun media logos/LOGOLSPRYDC-ezgif.com-jpg-to-webp-converter.webp", alt: "LSPR YDC" },
    { src: "/jmun media logos/logotransparentgmunc-ezgif.com-jpg-to-webp-converter.webp", alt: "Transparent GMUNC" },
    { src: "/jmun media logos/LogoYouthRangerJakarta-Gelap-ezgif.com-jpg-to-webp-converter.webp", alt: "Youth Ranger Jakarta Gelap" },
    { src: "/jmun media logos/MIDPLogo4-ezgif.com-jpg-to-webp-converter.webp", alt: "MIDP Logo" },
    { src: "/jmun media logos/presmun-removebg-preview.webp", alt: "Presmun" },
    { src: "/jmun media logos/quintessence_mun-removebg-preview.webp", alt: "Quintessence MUN" },
    { src: "/jmun media logos/sparkmun_logo-removebg-preview.webp", alt: "Spark MUN" },
    { src: "/jmun media logos/sre_ui-removebg-preview (1).webp", alt: "SRE UI" },
    { src: "/jmun media logos/sreits-ezgif.com-jpg-to-webp-converter.webp", alt: "SRE ITS" },
    { src: "/jmun media logos/SUMUN-removebg-preview.webp", alt: "SUMUN" },
    { src: "/jmun media logos/sxcsemarang-ezgif.com-jpg-to-webp-converter.webp", alt: "SXC Semarang" },
    { src: "/jmun media logos/SyahidMUNClub-ezgif.com-jpg-to-webp-converter.webp", alt: "Syahid MUN Club" },
    { src: "/jmun media logos/togethermun_kr-removebg-preview.webp", alt: "Together MUN KR" },
    { src: "/jmun media logos/UGMMUNCommunity-ezgif.com-jpg-to-webp-converter.webp", alt: "UGM MUN Community" },
    { src: "/jmun media logos/UNEJ_MUN-removebg-preview.webp", alt: "UNEJ MUN" },
    { src: "/jmun media logos/UnhasMUNCommunity-ezgif.com-jpg-to-webp-converter.webp", alt: "Unhas MUN Community" },
    { src: "/jmun media logos/VeteranJogjakartaMUN-ezgif.com-jpg-to-webp-converter.webp", alt: "Veteran Jogjakarta MUN" },
];
