export const news_list = [
  {
    author: "[Name of Delegate] of the [Agency]",
    title: "[Title] The real reasons freelancers are underpaid",
    desc: "[Desc] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum risus ac libero malesuada, at consectetur justo facilisis. Nam vulputate metus a lacus pharetra consectetur. Pellentesque dictum elit in bibendum suscipit. Morbi sit amet ornare tellus.",
    link: "https://doubleyourfreelancing.com/lesson-2-a6t/",
    image: "/backgrounds/bhi.webp",
    date: "[Date] Jun 18",
  },
  {
    author: "[Name of Delegate] of the [Agency]",
    title: "[Title] The real reasons freelancers are underpaid",
    desc: "[Desc] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum risus ac libero malesuada, at consectetur justo facilisis. Nam vulputate metus a lacus pharetra consectetur. Pellentesque dictum elit in bibendum suscipit. Morbi sit amet ornare tellus.",
    link: "https://doubleyourfreelancing.com/lesson-2-a6t/",
    image: "/backgrounds/bhi.webp",
    date: "[Date] Jun 18",
  },
  {
    author: "[Name of Delegate] of the [Agency]",
    title: "[Title] The real reasons freelancers are underpaid",
    desc: "[Desc] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum risus ac libero malesuada, at consectetur justo facilisis. Nam vulputate metus a lacus pharetra consectetur. Pellentesque dictum elit in bibendum suscipit. Morbi sit amet ornare tellus.",
    link: "https://doubleyourfreelancing.com/lesson-2-a6t/",
    image: "/backgrounds/bhi.webp",
    date: "[Date] Jun 18",
  },
  {
    author: "[Name of Delegate] of the [Agency]",
    title: "[Title] The real reasons freelancers are underpaid",
    desc: "[Desc] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum risus ac libero malesuada, at consectetur justo facilisis. Nam vulputate metus a lacus pharetra consectetur. Pellentesque dictum elit in bibendum suscipit. Morbi sit amet ornare tellus. ",
    link: "https://doubleyourfreelancing.com/lesson-2-a6t/",
    image: "/backgrounds/bhi.webp",
    date: "[Date] Jun 18",
  },
  {
    author: "[Name of Delegate] of the [Agency]",
    title: "[Title] The real reasons freelancers are underpaid",
    desc: "[Desc] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum risus ac libero malesuada, at consectetur justo facilisis. Nam vulputate metus a lacus pharetra consectetur. Pellentesque dictum elit in bibendum suscipit. Morbi sit amet ornare tellus.",
    link: "https://doubleyourfreelancing.com/lesson-2-a6t/",
    image: "/backgrounds/bhi.webp",
    date: "[Date] Jun 18",
  },
  {
    author: "[Name of Delegate] of the [Agency]",
    title: "[Title] The real reasons freelancers are underpaid",
    desc: "[Desc] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum risus ac libero malesuada, at consectetur justo facilisis. Nam vulputate metus a lacus pharetra consectetur. Pellentesque dictum elit in bibendum suscipit. Morbi sit amet ornare tellus.",
    link: "https://doubleyourfreelancing.com/lesson-2-a6t/",
    image: "/backgrounds/bhi.webp",
    date: "[Date] Jun 18",
  },
];
