export const sponsors = ['bi-logo.png', 'dinas-kebudayaan-logo.png', 'mandiri-logo.png', 'savera-logo.png'];
export const medias = [
	'kompas-logo.svg',
	'fpci-umy-logo.png',
	'fpci-ub-logo.png',
	'fpci-undip-logo.png',
	'fpci-ui-logo.png',
	'yoursay-logo.png',
	'unaindonesia-logo.png',
	'sxceo-logo.png',
	'mg-logo.png',
	'ltk-logo.png',
	'iyf-logo.png',
	'gw-logo.png',
	'aiesec-logo.webp',
	'ugmac-logo.jpg',
	'itbmun2023-logo.png',
	'alsa-logo.png',
	'itsmun-logo.png',
	'tiumun-logo.png',
	'joinmun2023-logo.svg',
];
